### ISSUE TITLE
Code error need help

### ISSUE THREAD

**Issue by ricktop123** [kyegomez/Med-PaLM#8]
When I run example.py, 
  File "/project/Med-PaLM/example.py", line 9, in <module>
    model = MedPalm()
  File "/project/Med-PaLM/medpalm/model.py", line 121, in __init__
    self.encoder = ViTransformerWrapper(

AttributeError: cannot assign module before Module.__init__() call

**Comment by ricktop123** [comment]
it seems the self.encoder didnot define above

**Comment by kyegomez** [comment]
@ricktop123 Hey please excuse me can you provide the full error log for me please.

**Comment by ricktop123** [comment]
> @ricktop123 Hey please excuse me can you provide the full error log for me please.

Traceback (most recent call last):
  File "/project/Med-PaLM/example.py", line 9, in <module>
    model = MedPalm()
  File "/project/Med-PaLM/medpalm/model.py", line 121, in __init__
    self.encoder = ViTransformerWrapper(
  File "/XXX/anaconda3/envs/MedPL/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1294, in __setattr__
    raise AttributeError(
AttributeError: cannot assign module before Module.__init__() call

**Comment by instabaines** [comment]
I encountered the same error

**Comment by kyegomez** [comment]
@ricktop123 @instabaines They are both fixed now, thanks for your patience!
